name: sail-kokokahi

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3. Install dependencies
    - name: Install Dependencies
      run: npm install

    # 4. Run ESLint
    - name: Run ESLint
      run: npm run lint
    
    # 5. Install Playwright browsers
    - name: Install Playwright browsers
      run: npx playwright install

    # 6. Run Playwright tests
    - name: Run Playwright Tests
      run: npm run test
